spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:${SUPABASE_HOST:db.wdhcvudeqkkxrfdvxgkj.supabase.co}}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}?sslmode=require
    username: ${POSTGRES_USER:${SUPABASE_USER:postgres}}
    password: ${POSTGRES_PASSWORD:${SUPABASE_PASSWORD:p0505251216#}}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        discord:
          webhook:
            url: ${DISCORD_WEBHOOK_URL:}

executive:
  secret-key: ${EXECUTIVE_SECRET_KEY:consensus2024!}